### ISSUE TITLE
D-Pad double click

### ISSUE THREAD

**Issue by renato-grottesi** [renato-grottesi/arduboy#20]
Move the building cursor to the next available spot to build the current building when double clicking the d-pad right or left button.

Separate the buildings into categories:
* Actions: (clear, upgrade, move, tnt, etc)
* Housing: house, farm, mill, water tower
* Stats: sheriff, church, saloon
* Environment: tree, weed, cactus

Double clicking the d-pad up or down buttons should move the current building to the next category.

**Comment by gsliepen** [comment]
Other movements that would be helpful to implement: recenter, move to left/right-most building. Since you can press both left and right simultaneously on the Arduboy, you could use that for centering at least.

**Comment by renato-grottesi** [comment]
I'll start working on the categorization of buildings and the up/down double clicking.

**Comment by renato-grottesi** [comment]
I created the categories and implemented the double clicking up and down.
