### ISSUE TITLE
Add day/night cycle

### ISSUE THREAD

**Issue by gsliepen** [renato-grottesi/arduboy#29]
The display controller can be told to invert the whole display. So we can easily flip between black-on-white and white-on-black without having to change any of the level rendering functions. We can replace the mountains with stars during the night. We can also render a sun during day and moon during night.

Some events could be made more likely to happen depending on the time of day, like robberies.

**Comment by renato-grottesi** [comment]
I thought about the day/night transition before, but I was afraid that a sudden switch using the display controller could be confusing for the player.
Maybe we could use a 2 seconds transition with some dithering where the game freezes and the time of the day transition a bit more smoothly?

**Comment by gsliepen** [comment]
That could work. Maybe the mountain drawing can be changed to draw shaded mountains + a sky gradient that depends on the time of day. If done smart, it could replace the arduboy.clear() function entirely.

**Comment by renato-grottesi** [comment]
I added Level::days to hook your day/night cycles.
It will update the stats screen.
