### ISSUE TITLE
Disasters

### ISSUE THREAD

**Issue by gsliepen** [renato-grottesi/arduboy#30]
To keep things interesting later in the game, introduce disasters. These could either be triggered by the player reaching some milestone (lots of gold/people/etc), or after some fixed or random time. Possible instantenous disasters:

* Flood: random buildings in flood area are destroyed
* Earthquake: same as above
* Hurricane: same as above
* Meteor strike: cluster of buildings is destroyed

Maybe we can have disasters that last a while:

* Invasion: some tribe goes to war, causing population loss or stealing money. Needs a lot more sheriffs to fend off.
* Drought: water towers are ineffective
* Blight: food production halved, no income from exports
* Snowed in: mountain pass inaccessible, no income from exports, no people can join Lagunita

Any other ideas?

**Comment by renato-grottesi** [comment]
I added the land slide when the environment is not 100%.
I don't think that we can easily add more events with the remaining 1KB of flash memory, especially considering that we would need some text to explain what it going on...
Should we compress the text to make space?

**Comment by renato-grottesi** [comment]
There isn't space left to implement more disasters after increasing the help section.
